import type { Square } from './types';

export const squares: Square[] = [
  { description: 'eat 3 poison boluses', category: 'common' },
  { description: 'Dogs', category: 'nightlord' },
  { description: 'Scarlet rot place', category: 'map-type' },
  {
    description: 'beat a boss without using skill',
    category: 'character-specific',
    nightfarerSpecific: 'recluse',
  },
  { description: 'drink 2 pickled thing', category: 'common' },
  { description: 'kill 4 daggers', category: 'common' },
  { description: 'eat 1 pickled thing', category: 'common' },
  { description: 'drink 3 bolluses', category: 'common' },
  { description: 'kill 2 pickled thing', category: 'common' },
  { description: 'eat 4 daggers', category: 'common' },
  { description: 'drink 2 daggers', category: 'common' },
  { description: 'kill 1 bolluses', category: 'common' },
  { description: 'drink 1 pickled thing', category: 'common' },
  { description: 'kill 5 daggers', category: 'common' },
  { description: 'eat 2 daggers', category: 'common' },
  { description: 'drink 3 pickled thing', category: 'common' },
  { description: 'kill 3 bolluses', category: 'common' },
  { description: 'eat 5 bolluses', category: 'common' },
  { description: 'drink 4 pickled thing', category: 'common' },
  { description: 'kill 3 pickled thing', category: 'common' },
  { description: 'eat 1 daggers', category: 'common' },
  { description: 'kill 4 bolluses', category: 'common' },
  { description: 'eat 3 pickled thing', category: 'common' },
  { description: 'drink 5 bolluses', category: 'common' },
  { description: 'kill 2 daggers', category: 'common' },
  { description: 'drink 1 bolluses', category: 'common' },
  { description: 'eat 2 pickled thing', category: 'common' },
  { description: 'kill 1 daggers', category: 'common' },
  { description: 'drink 2 bolluses', category: 'common' },
  { description: 'kill 2 bolluses', category: 'common' },
  { description: 'drink 4 bolluses', category: 'common' },
  { description: 'eat 4 pickled thing', category: 'common' },
  { description: 'kill 5 bolluses', category: 'common' },
  { description: 'eat 5 pickled thing', category: 'common' },
  { description: 'drink 5 pickled thing', category: 'common' },
  { description: 'eat 3 daggers', category: 'common' },
  { description: 'kill 3 daggers', category: 'common' },
  { description: 'drink 3 daggers', category: 'common' },
  { description: 'eat 2 bolluses', category: 'common' },
  { description: 'kill 4 pickled thing', category: 'common' },
  { description: 'eat 1 bolluses', category: 'common' },
  { description: 'drink 2 pickled thing', category: 'common' },
  { description: 'kill 1 pickled thing', category: 'common' },
  { description: 'castle place', category: 'map-type' },
  { description: 'Bugs', category: 'nightlord' },
  {
    description: 'beat dungeon without healing',
    category: 'character-specific',
    nightfarerSpecific: 'raider',
  },
  {
    description: 'never use flask entire area',
    category: 'character-specific',
    nightfarerSpecific: 'duchess',
  },
  { description: 'Snowy hills', category: 'map-type' },
  { description: 'Horse', category: 'nightlord' },
  { description: 'Rot swamp', category: 'map-type' },
  {
    description: 'jump only to boss',
    category: 'character-specific',
    nightfarerSpecific: 'duchess',
  },
  {
    description: 'no summons boss fight',
    category: 'character-specific',
    nightfarerSpecific: 'raider',
  },
];
